version: '3.8'

services:
  wiremock:
    image: wiremock/wiremock:3.3.1
    container_name: supplier-api-mock
    ports:
      - "9090:8080"
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings
    command:
      - --verbose
